name: Update Project Data

on:
  push:                 # Runs whenever you push a commit
    branches:
      - main
  schedule:             # Runs automatically every 24 hours
    - cron: "0 0 * * *"
  workflow_dispatch:    # Allows manual trigger from GitHub Actions UI

jobs:
  update-projects:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # ✅ Required for custom authentication

      - name: Create data directory
        run: mkdir -p data  # ✅ Ensures data/ folder exists

      - name: Fetch Projects Repository Data
        run: |
          curl -H "Authorization: token ${{ secrets.PORTFOLIO_PAGE_TOKEN }}" \
               -H "User-Agent: evocation01" \
               "https://api.github.com/repos/evocation01/projects/contents" \
               | jq '.' > data/projects.json

      - name: Fetch Data Science Repository Data
        run: |
          curl -H "Authorization: token ${{ secrets.PORTFOLIO_PAGE_TOKEN }}" \
               -H "User-Agent: evocation01" \
               "https://api.github.com/repos/evocation01/data-sci/contents" \
               | jq '.' > data/data-sci.json

      - name: Fetch Power BI Repository Data
        run: |
          curl -H "Authorization: token ${{ secrets.PORTFOLIO_PAGE_TOKEN }}" \
               -H "User-Agent: evocation01" \
               "https://api.github.com/repos/evocation01/power-bi/contents" \
               | jq '.' > data/power-bi.json

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add data/projects.json data/data-sci.json data/power-bi.json
          git commit -m "🔄 Auto-update project data" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.PORTFOLIO_PAGE_TOKEN }}@github.com/evocation01/evocation01.github.io.git main
